### ISSUE TITLE
Modificar dashboard de cara los lpro days

### ISSUE THREAD

**Issue by dpeite** [dpeite/JustTelemetry#108]
* Cambiar grafica por grafica de barras con numero de sesiones en un dia.
* Cambiar panel de notificaciones, para solo dejar los errores.

**Comment by ManuLG** [comment]
1. He hardcodeado varias notificaciones de prueba en el panel. 
2. He modificado el gráfico para que sea de barras y muestre la información de un fichero JSON, dash.json

    1. He creado un fichero index.js que hace un petición a la web y obtiene un JSON de la forma:
```json
{
    "dd/mm/yyyy" : "n",
    "dd/mm/yyyy" : "n",
    "dd/mm/yyyy" : "n"
}
```
Sólo necesitas pasárselo a la gráfica de flot charts y listo.

**Comment by dpeite** [comment]
Falta cambiar la grafica para usar flot charts
