### ISSUE TITLE
Definir las variables del estado

### ISSUE THREAD

**Issue by ManuLG** [dpeite/JustTelemetry#15]
Cada estado de Kalman tiene un número de variables. Debemos definirlo cuanto antes.

**Comment by ManuLG** [comment]
Estoy viendo que será necesario añadir una variable más al vector de estados, la medida del giroscopio, aunque no lo usemos directamente. Así también se le aplicará Kalman y obtendremos medidas similares a cuando creamos el Kalman para el giroscopio.

 Otra opción interesante puede ser añadir directamente la orientación al vector, pero habría que ver cómo lo planteamos.

**Comment by 0skiC** [comment]
A final, hemos optado por hacer un kalman unidimensional debido a:
* Así no volvemos a cambiar las librerías ya acabadas de las matrices.
* Consume menos memoria porque no tenemos que añadir una dimensión más a cada matriz.
* Ya teníamos hecho de antemano el kalman unidimensional, y sus operaciones están optimizadas.
