### ISSUE TITLE
Traducción de coordenadas a metros

### ISSUE THREAD

**Issue by ManuLG** [dpeite/JustTelemetry#16]

**Comment by ManuLG** [comment]
Perfecto, comenta los resultados que obtengas

**Comment by 0skiC** [comment]
![Aquí está la solución:](https://lh3.googleusercontent.com/gLZJ4qOngO4DY0u56hg0KxhuFtDwRipAFSwvOuL8yNAvcnd3Zd6fEkADVPvsLjX1MspMahqaTEDPVl6jHn3P8HZQqWNL3-F3X3-FhpyAa17XkQkV0RH09nkmIDaUdU6K400ln2wSJNgstaDuJDrHPWSAYkD0NCb57NbjJaQNMC7KaxhtUtDuvDLsZAYHRvkG8dpz52oMJfZz3sp5BER8YmuVJxa3xdTPa0Kl2um_P41NYudkGu0e2hq6yU-HtkMdwTiI1PDLWQmxL028kRhW3y7ED4LkYdAQvG_bxmmZAWWpf7_2EYZ7K3WYVLbVTZ9h96mbXt2T4O0ChoyzYa5B4a_hw4pWCwnNCXse3d-7kj_e4Y_j4_wT3WiboX6Fl900SjEqhAQAWa3FkjGL4lurx3IOWTI3nj-9cCiAsoZTKPUn8STAF1J7v7isqj_NTolM1deOsFPMdthrCz-gE7OgdlGlwLr3bOudN9ypj5G9udwllqowS8y5IYtV29tFQ59Y91g1pf_Nv9wqRgWG-_rcmlk5z_xOTTa2jx-hZacvTbFei09ttybzkRX8B5w-IMDQn639bhFdPrgwZ2kHtuavHtv0o4t0QZyDN1RCpOxMhF7h3_YPzzEo=w554-h738-no "Solución")
