### ISSUE TITLE
Posibilidad de importar y exportar los datos

### ISSUE THREAD

**Issue by dpeite** [dpeite/JustTelemetry#21]
Como mejora podríamos hacer que sea posible la importación y exportación de los datos. Ademas, podríamos añadir campos extras con informacion como:

* Nombre
* Hora
* Km recorridos
* Notas

**Comment by dpeite** [comment]
En este commit, esta añadida la funcion de descarga de la sesiones https://github.com/dpeite/JustTelemetry/commit/3fda4749931009db7283d27ac6cfed67d48029b8

**Comment by dpeite** [comment]
Falta por hacer pestaña para pedir a una api rest los datos del coche.

**Comment by ManuLG** [comment]
Actualmente está implementada la pestaña de importar desde fichero y de importar desde IP. Si se importa desde IP se comprueba la IP y, en caso de ser correcta, manda la petición al servidor. Falta implementar la lógica por detrás.

PD: Los commits están referenciados en la issue #26 por error
