### ISSUE TITLE
Diseñar el circuito 

### ISSUE THREAD

**Issue by ManuLG** [dpeite/JustTelemetry#37]
Es necesario hacer la lista de componentes, dibujar las conexiones entre ellos y diseñar el PCB para imprimirlo en el laboratorio de la escuela. 

Además estaría bien hacer una lista de especificaciones del PCB (intensidad que consume en total,  voltaje de cada elemento, etc).

**Comment by ManuLG** [comment]
# Primera versión del circuito

![image](https://cloud.githubusercontent.com/assets/16776395/23946827/4fd38480-097c-11e7-96be-37232d0312cc.png)

Óscar nos ha recomendado los siguientes cambios en el diseño:
* Hacer las rutas más anchas, ya que tenemos espacio de sobra.
* Añadir condensadores a la entrada y a la salida del regulador de tensión.
* Intentar que los agujeros tengan forma elipsoidal para así tener más cobre.
* Hacer más grandes las conexiones de los conectores de alimentación y UART para que al taladrar quede cobre de sobra.

Por otro lado, al hablar con Nacho (responsable del laboratorio de PCBs de Teleco) me ha dicho, aparte de las que ya nos había dicho Óscar, algún consejo más:

* Los giros de las rutas que sean de 45º+45º en lugar de 90º
* En lugar de usar el regulador de tensión que ibamos a usar (del tipo [LD1117](https://www.sparkfun.com/datasheets/Components/LD1117V33.pdf)) plantearnos uno tipo SMD con el encapsulado [TO-252](http://uk.farnell.com/texas-instruments/ua78m33ckvurg3/volt-reg-3-3v-to-252/dp/2075446), ya que disiparía el calor hacia la placa.
* Hacer "plano de masa" el PCB. Esto significa que todo el PCB sería tierra, lo que supondría ahorrarse las rutas de tierra y además nos protegería de las interferencias.


A mayores de los consejos para mejorar el diseño, se han encontrado los siguientes fallos:
* No había conexión entre GND de la alimentación y el del Arduino.

**Comment by ManuLG** [comment]
# Segunda versión del circuito

![image](https://cloud.githubusercontent.com/assets/16776395/23958930/fcb20da8-09a3-11e7-9a29-f980f4e6bb07.png)

Hemos realizado las siguientes modificaciones:
* Hemos transformado los giros de 90º en giros de 45º más 45º.
* Hemos añadido los dos condesadores necesarios. Según la datasheet del regulador son necesarios dos condensadores de 10uF de Tantalum.
* Hemos ancheado las pistas al máximo permitido, excepto una porque quedaba muy cerca de otra.
* No hemos podido encontrar los agujeros con el cobre en forma de elipse, pero hemos aumentado un poco el cobre alrededor del agujero.
* Hemos aumentado más el cobre alrededor de los conectores de alimentación, para que al hacer el agujero quede cobre suficiente. 


# Versión alternativa, con plano de masa

![image](https://cloud.githubusercontent.com/assets/16776395/23959413/6e8fda6c-09a5-11e7-86c9-60b077eff1be.png)

Tiene las mismas modificaciones que el anterior, pero tiene plano de masa en ambas caras y hemos eliminado las rutas de tierra por no ser necesarias. Hemos exportado el PCB como PDF para comprobar que las conexiones estuviesen bien y lo están.

**Comment by 0skiC** [comment]
# Especificaciones técnicas:

### Intensidad:
* Arduino: 500mA aproximadamente.
* Módulo GPS: 90mA.                 
* Acelerómetro: 450μA.               
* Giroscopio: 3,2mA.                    
* Magnetómetro: 280μA.             
* Total: 593,93mA ≈ 600mA      


### Voltaje:
* Arduino: 6-20V (máximo); 7-12V (recomendado).
* Módulo GPS: 2,7-3,3V.
* Acelerómetro, Giroscopio & Magnetómetro: 2,4-3,6V


### Potencia disipada por el regulador:
P(w) = (Vin - Vout) * I1 = (12V - 3,3V) * 93,93mA = 0,817191 Watts
Siendo 93,93mA la suma de las intensidades de los componentes a excepción del Arduino.



### Temperatura máxima:
#### [LM1117T](https://www.taydaelectronics.com/lm1117t-lm1117-low-dropout-voltage-regulator-ic-3-3v.html)
* T(ºC) = P * Rterm + Tamb = 0,817191W * 82ºC/W + 25ºC = 92 ºC (sin disipador).

#### [UA78M33QDCYRG4Q1](http://es.farnell.com/texas-instruments/ua78m33qdcyrg4q1/reg-tensi-n-lin-3-3v-0-5a-sot/dp/2463957)
*  T(ºC) = P * Rterm + Tamb = 0,817191W * 57ºC/W + 25ºC = 71,58 ºC.
