### ISSUE TITLE
Primera sesión de pruebas del sistema de posicionamiento

### ISSUE THREAD

**Issue by 0skiC** [dpeite/JustTelemetry#40]
Vamos a realizar las siguientes pruebas:

* Realizar 3 vueltas seguidas a un "circuito".
* Realizar una vuelta en la que pongamos a 0 la velocidad y aceleración en el momento en el que no detectemos movimiento.
* Probar diferentes configuraciones para el smartdelay().
* Probar a invertir el eje Y para solucionar el problema de imagen.
* Comprobar los valores de inicialización para el giroscopio.
En función del resultado anterior, probaremos a tomar las medidas de orientación con el giroscopio.

**Comment by ManuLG** [comment]
# Resultados de la prueba

 Hemos realizado las pruebas en el parking de la Escuela de Ingeniería industrial, concretamente esta zona:
![image](https://cloud.githubusercontent.com/assets/16776395/24071842/bbe2fdac-0bdb-11e7-85ee-b252bbd25a25.png)


### Realizar tres vueltas seguidas al circuito
![image](https://cloud.githubusercontent.com/assets/16776395/24071815/5bdd5ff6-0bdb-11e7-8e4a-58dde23f1b9e.png)

* A la vista de la imagen vemos que la forma del circuito es la correcta pero que aparece invertido respecto al trazado real.
* La posición final es (-0.87609462, -0.48322882), siendo unos muy buenos resultados.
* Vemos que la trazada presenta un aspecto ruidoso (seguramente provocado por culpa del GPS, ya que es el mismo ruido que apareció cuando le aumentamos la tasa de actualización al módulo) que debemos intentar minimizar. 
* Otro aspecto a tener en cuenta es la orientación inicial. Se observa claramente que la linea correspondiente al inicio de la prueba está más separada que el resto hasta llegar a la curva, momento en el que se junta con las demás. Deberíamos ver por qué sucede e intentar mejorarlo en la medida de lo posible.

### Realizar una vuelta en la que pongamos a 0 el valor de los sensores cuando no detectemos cambios en la posición
![image](https://cloud.githubusercontent.com/assets/16776395/24071931/901fa812-0bdd-11e7-9675-b48ab048fa04.png)
* Finalmente hemos realizado dos vueltas en lugar de una.
* La trazada de las distintas vueltas coincide más, debemos hacer más pruebas para comprobar si es por este cambio o porque al haber pasado cierto tiempo con el GPS encendido ha cogido más satélites
* Relacionado con este punto, podríamos idear una forma de modificar la incertidumbre del GPS (a mayores de lo que ya haga Kalman) en función del número de satélites de los que reciba señal el módulo (dato que nos da la librería).
* Otra opción que debemos probar es poner sólo a 0 la aceleración, dado que es posible que el coche "rote" sin moverse del sitio (por ejemplo, porque lo levanten en peso o algo del estilo. No sé si es factible pero creo que habría que tenerlo en cuenta).


### Probar distintas configuraciones del método smartdelay()
El método smartdelay() forma parte de la librería del GPS, y es donde se parsean las frases en formato NMEA que nos da el módulo GPS. El código es el siguiente:

```c
static void smartdelay(unsigned long ms)
{
  unsigned long start = millis();
  do
  {
    while (Serial1.available())
      gps.encode(Serial1.read());
  } while (millis() - start < ms);
}
```

 Hemos llegado a la conclusión de que el parametro que recibe es el tiempo entre actualizaciones del GPS (en nuestro caso 100ms). Como nosotros necesitamos que todo el proceso dure 100ms vamos a comprobar que ocurre si le introducimos un valor de 50ms a la función.

![image](https://cloud.githubusercontent.com/assets/16776395/24072075/baed57d0-0be0-11e7-9671-a80b4ecfdb9a.png)

A priori no parece que haya ningún problema por usar ese valor, así que lo mantendremos. Si en un futuro necesitamos bajarlo todavía más para cumplir los requisitos temporales haremos más pruebas para comprobar que sea viable. 

### Probar a invertir el eje Y para solucionar el problema de imagen
Hasta ahora hemos visto que la trazada parece "reflejada" y no se corresponde por completo con la realidad. Hemos hecho varias pruebas, y los resultados son:

* Multiplicando px por -1
![image](https://cloud.githubusercontent.com/assets/16776395/24073090/e389a7dc-0bf1-11e7-8a11-b8b023223956.png)

* Multiplicando px y vx por -1
![image](https://cloud.githubusercontent.com/assets/16776395/24073105/2504d114-0bf2-11e7-8534-5837736771c6.png)

* Multiplicando la vx por -1
![image](https://cloud.githubusercontent.com/assets/16776395/24073116/6b7f368e-0bf2-11e7-8901-14ad3cd9d7c3.png)

 A la vista de las imágenes vemos que lo que debemos hacer para corregir la inversión de la imagen es multiplicar la componente px por menos uno.

### Comprobar los valores de inicialización para el giroscopio

 Hemos comprobado que los valores del giroscopio se innicializan a 0 independientemente de la posición inicial.
