### ISSUE TITLE
La selección de puntos en la trazada debería de ser reversible

### ISSUE THREAD

**Issue by dpeite** [dpeite/JustTelemetry#62]
Actualmente la selección de un trozo de la trazada solo funciona si se escogen los puntos en el sentido que se recorrió la vuelta. Estaría bien hacer que fuese independiente de que punto se selecciona primero.

**Comment by ManuLG** [comment]
Lo que he hecho es que si no hay datos que mostrar en la gráfica se invierten las coordenadas y se repite el proceso.

 La forma más eficiente de hacerlo sería de una única vez comprobando si coincide con la primeras o las últimas
