### ISSUE TITLE
Poner un icono de carga mientras se procesan los ficheros de las vueltas

### ISSUE THREAD

**Issue by ManuLG** [dpeite/JustTelemetry#86]
En la pestaña de sesiones, si finalmente se recortan todos los ficheros desde el primer momento, estaría bien poner un icono animado indicando que está cargando ([ejemplos de Font Awesome](http://fontawesome.io/examples/#animated)); no debería ser complicado y desde el JS se sabe que comienza a cortar a partir de [aquí ](https://github.com/dpeite/JustTelemetry/blob/modificar_plantilla/app/static/js/sesiones.js#L55) y termina justo antes de llegar a [aquí](https://github.com/dpeite/JustTelemetry/blob/modificar_plantilla/app/static/js/sesiones.js#L58).

**Comment by dpeite** [comment]
No soy capaz de centrarlo verticalmente, de momento queda así.
